CREATE DATABASE bsn_spartan_dc DEFAULT CHARACTER SET utf8 COLLATE = utf8_general_ci;

use bsn_spartan_dc;

DROP TABLE
    IF EXISTS dc_user;

CREATE TABLE dc_user (
                         user_id BIGINT NOT NULL auto_increment,
                         contacts_email VARCHAR (60) NOT NULL DEFAULT '' COMMENT 'Email Address',
                         contacts_name VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'Contact',
                         contacts_phone VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'Phone',
                         state SMALLINT NOT NULL DEFAULT 1 COMMENT 'Status   1: Enabled   0: Disabled',
                         create_time datetime COMMENT 'Created time',
                         salt VARCHAR (32) NOT NULL DEFAULT '' COMMENT 'Salt',
                         PASSWORD VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'Password',
                         PRIMARY KEY (user_id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT 'User Information List';

DROP TABLE
    IF EXISTS ntt_tx_record;

CREATE TABLE ntt_tx_record (
                               tx_record_id BIGINT NOT NULL auto_increment,
                               tx_hash VARCHAR (100) NOT NULL DEFAULT '' COMMENT 'Transaction Hash',
                               operator VARCHAR (100) NOT NULL DEFAULT '' COMMENT 'Sender address',
                               type SMALLINT NOT NULL DEFAULT 1 COMMENT 'Type   0: Node Establishment Incentive Program  1  : Data Center Monthly Incentive Program    3: Top up Gas Credit   4: Top up NTT   7: Refund for Gas Credit top-up failed',
                               from_address VARCHAR (100) NOT NULL DEFAULT '' COMMENT 'Sender wallet address ',
                               to_address VARCHAR (100) NOT NULL DEFAULT '' COMMENT ' Receiver wallet address',
                               ntt_count DECIMAL (56, 12) NOT NULL DEFAULT 0 COMMENT 'Nubmer of NTTs',
                               from_ntt_balance DECIMAL (56, 12) NOT NULL DEFAULT 0 COMMENT 'Sender wallet balance ',
                               to_ntt_balance DECIMAL (56, 12) NOT NULL DEFAULT 0 COMMENT ' Receiver wallet balance',
                               tx_time datetime COMMENT 'Transaction time',
                               create_time datetime COMMENT 'Created time',
                               md5_sign VARCHAR (64) DEFAULT '' COMMENT 'The hash value generated by MD5 algorithm of the data obtained from the parsed block',
                               PRIMARY KEY (tx_record_id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT 'NTT transaction table';

DROP TABLE
    IF EXISTS event_block;

CREATE TABLE event_block (
                             block_height BIGINT NOT NULL DEFAULT 0 COMMENT 'Block height',
                             PRIMARY KEY (block_height)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT 'Event parsing block height';

DROP TABLE
    IF EXISTS chain_price;

CREATE TABLE chain_price (
                             chain_price_id BIGINT NOT NULL auto_increment,
                             chain_id BIGINT,
                             ntt_count NUMERIC (56, 12) NOT NULL DEFAULT 1 COMMENT 'NTT',
                             gas NUMERIC (56, 12) NOT NULL DEFAULT 0 COMMENT 'Gas Credit price',
                             create_time datetime COMMENT 'Created time',
                             PRIMARY KEY (chain_price_id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT 'Price information';

DROP TABLE
    IF EXISTS sys_data_center;

CREATE TABLE sys_data_center (
                                 dc_id BIGINT NOT NULL auto_increment COMMENT 'Data Center ID',
                                 contacts_email VARCHAR (60) NOT NULL DEFAULT '' COMMENT 'Email Address',
                                 ntt_account_address VARCHAR (100) NOT NULL DEFAULT '' COMMENT 'NTT Wallet Address',
                                 token VARCHAR (500) NOT NULL DEFAULT '' COMMENT 'Token',
                                 dc_code VARCHAR (20) NOT NULL DEFAULT '' COMMENT 'ID',
                                 create_time datetime COMMENT 'Created time',
                                 PRIMARY KEY (dc_id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT 'Data Center Information Table';

DROP TABLE
    IF EXISTS dc_chain;

CREATE TABLE dc_chain (
                          chain_id BIGINT NOT NULL auto_increment,
                          chain_type VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'Chain Type',
                          chain_name VARCHAR (100) NOT NULL DEFAULT '' COMMENT 'Chain Name',
                          recharge_unit VARCHAR (10) NOT NULL DEFAULT '' COMMENT 'unit',
                          PRIMARY KEY (chain_id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT 'Data Center - Chain Information Table';

DROP TABLE
    IF EXISTS chain_account_recharge_meta;

CREATE TABLE chain_account_recharge_meta (
                                             recharge_meta_id BIGINT NOT NULL auto_increment,
                                             chain_account_address VARCHAR (100) COMMENT 'Wallet Address',
                                             gas NUMERIC (50, 0) NOT NULL DEFAULT 0 COMMENT 'Topped-up Gas Credit',
                                             deadline BIGINT NOT NULL DEFAULT 0 COMMENT 'Transaction Expiration Time',
                                             sign VARCHAR (500) NOT NULL DEFAULT '' COMMENT 'Signature    Byte value compiled by base64',
                                             PRIMARY KEY (recharge_meta_id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT 'Emergency Top-up Gas Credit Information Table';

DROP TABLE
    IF EXISTS dc_gas_recharge_record;

CREATE TABLE dc_gas_recharge_record (
                                        recharge_record_id BIGINT NOT NULL auto_increment,
                                        chain_id BIGINT,
                                        chain_address VARCHAR (100) NOT NULL COMMENT 'Wallet Address',
                                        gas NUMERIC (50) NOT NULL DEFAULT 0,
                                        recharge_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Top-up Time',
                                        state SMALLINT NOT NULL DEFAULT 0 COMMENT 'Top-up submission status   1: Pending    2: In Progress    3: Submitted    4: Failed',
                                        tx_hash VARCHAR (200) DEFAULT NULL COMMENT 'Transaction hash',
                                        update_time datetime DEFAULT NULL COMMENT 'Update time',
                                        recharge_code VARCHAR (64) NOT NULL DEFAULT '' COMMENT 'Top-up ID: the event is returned from the chain',
                                        ntt NUMERIC (56, 12) COMMENT 'NTT consumed by topping up Gas Credit  Event parsing data',
                                        recharge_result VARCHAR (500) COMMENT 'Result:  if success, returns the transaction hash; if failed, returns the reason',
                                        recharge_state SMALLINT NOT NULL DEFAULT 3 COMMENT 'Top-up status   0: In Progress   1: Success    2: Failed  3: No processing required',
                                        nonce BIGINT NOT NULL DEFAULT 0 COMMENT "nonce of emergency Gas Credit top-up, corresponding to the table's primary key",
                                        md5_sign VARCHAR (64) DEFAULT '' COMMENT 'The hash value generated by MD5 algorithm of the data obtained from the parsed block',
                                        PRIMARY KEY (recharge_record_id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT 'Gas Credit top-up record table  (End-user Gas Credit top-up + emergency Gas Credit top-up (event parsing))';

DROP TABLE
    IF EXISTS dc_node;

CREATE TABLE `dc_node` (
                           `node_id` BIGINT (20) NOT NULL AUTO_INCREMENT,
                           `chain_id` BIGINT (20) DEFAULT NULL,
                           `node_code` VARCHAR (200) NOT NULL DEFAULT '' COMMENT 'Node ID',
                           `rpc_address` VARCHAR (100) NOT NULL DEFAULT '' COMMENT 'RPC address',
                           `node_address` VARCHAR (500) NOT NULL DEFAULT '' COMMENT 'Node address',
                           `apply_sign` VARCHAR (500) NOT NULL DEFAULT '' COMMENT 'Node registration data signature',
                           `state` SMALLINT (6) NOT NULL DEFAULT '0' COMMENT 'Status  0: Pending   1: Submitted 2: Node registration testing   3: Failed    4: Success',
                           `remarks` VARCHAR (500) DEFAULT NULL COMMENT 'Remarks',
                           `create_time` datetime NOT NULL COMMENT 'Date applied',
                           `tx_hash` VARCHAR (100) DEFAULT NULL COMMENT 'Transaction Hash',
                           `tx_time` datetime DEFAULT NULL COMMENT 'Transaction time',
                           `apply_result_time` datetime DEFAULT NULL COMMENT 'Date of notifying the node registration application result',
                           `apply_result_tx_hash` VARCHAR (100) DEFAULT NULL COMMENT 'Transaction hash of the node registration application',
                           `ntt_count` DECIMAL (56, 12) DEFAULT '0.000000000000' COMMENT 'Amount of NTT Incentives',
                           `reason` VARCHAR (500) DEFAULT ' ' COMMENT 'Reason',
                           PRIMARY KEY (`node_id`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8 COMMENT = 'Full Node Information Table';

DROP TABLE
    IF EXISTS ntt_tx_sum;

CREATE TABLE ntt_tx_sum (
                            `ntt_tx_sum_id` BIGINT (20) NOT NULL AUTO_INCREMENT COMMENT 'ntt_tx_sum_id',
                            `flow_in` DECIMAL (56, 12) NOT NULL DEFAULT '0.000000000000' COMMENT 'in',
                            `flow_out` DECIMAL (56, 12) NOT NULL DEFAULT '0.000000000000' COMMENT 'out',
                            PRIMARY KEY (`ntt_tx_sum_id`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8 COMMENT = 'NTT transaction summary';




INSERT INTO `dc_chain` (`chain_id`, `chain_type`, `chain_name`, `recharge_unit`)
VALUES ('1', 'ETH', 'Spartan-I Chain (Powered by NC Ethereum)', 'GWEI'),
       ('2', 'Cosmos', 'Spartan-II Chain (Powered by NC Cosmos)', 'UGAS'),
       ('3', 'Polygon', 'Spartan-III Chain (Powered by NC PolygonEdge)', 'GWEI');