package com.spartan.dc.output.nodeManage.dto.fisco;


public class ContractDto {
    // Contract Name
    private String contractName;
    // The content of abi file generated by contract compilation
    private String contractAbi;
    // Contract's bytecode binary
    private String bytecodeBin;

    public String getContractName() {
        return contractName;
    }

    public void setContractName(String contractName) {
        this.contractName = contractName;
    }

    public String getContractAbi() {
        return contractAbi;
    }

    public void setContractAbi(String contractAbi) {
        this.contractAbi = contractAbi;
    }

    public String getBytecodeBin() {
        return bytecodeBin;
    }

    public void setBytecodeBin(String bytecodeBin) {
        this.bytecodeBin = bytecodeBin;
    }
}
