CREATE
DATABASE bsn_spartan_dc DEFAULT CHARACTER SET utf8 COLLATE = utf8_general_ci;

use
bsn_spartan_dc;


CREATE TABLE dc_user
(
    user_id        BIGINT      NOT NULL auto_increment,
    contacts_email VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'Email Address',
    contacts_name  VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'Contact',
    contacts_phone VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'Phone',
    state          SMALLINT    NOT NULL DEFAULT 1 COMMENT 'Status   1: Enabled   0: Disabled',
    create_time    datetime COMMENT 'Created time',
    salt           VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'Salt',
    PASSWORD       VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'Password',
    PRIMARY KEY (user_id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT 'User Information List';


CREATE TABLE ntt_tx_record
(
    tx_record_id     BIGINT          NOT NULL auto_increment,
    tx_hash          VARCHAR(100)    NOT NULL DEFAULT '' COMMENT 'Transaction Hash',
    operator         VARCHAR(100)    NOT NULL DEFAULT '' COMMENT 'Sender address',
    type             SMALLINT        NOT NULL DEFAULT 1 COMMENT 'Type   0: Node Establishment Incentive Program  1  : Data Center Monthly Incentive Program    3: Top up Gas Credit   4: Top up NTT   7: Refund for Gas Credit top-up failed',
    from_address     VARCHAR(100)    NOT NULL DEFAULT '' COMMENT 'Sender wallet address ',
    to_address       VARCHAR(100)    NOT NULL DEFAULT '' COMMENT ' Receiver wallet address',
    ntt_count        DECIMAL(56, 12) NOT NULL DEFAULT 0 COMMENT 'Nubmer of NTTs',
    from_ntt_balance DECIMAL(56, 12) NOT NULL DEFAULT 0 COMMENT 'Sender wallet balance ',
    to_ntt_balance   DECIMAL(56, 12) NOT NULL DEFAULT 0 COMMENT ' Receiver wallet balance',
    tx_time          datetime COMMENT 'Transaction time',
    create_time      datetime COMMENT 'Created time',
    md5_sign         VARCHAR(64)              DEFAULT '' COMMENT 'The hash value generated by MD5 algorithm of the data obtained from the parsed block',
    PRIMARY KEY (tx_record_id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT 'NTT transaction table';


CREATE TABLE event_block
(
    block_height BIGINT NOT NULL DEFAULT 0 COMMENT 'Block height',
    PRIMARY KEY (block_height)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT 'Event parsing block height';


CREATE TABLE chain_price
(
    chain_price_id BIGINT          NOT NULL auto_increment,
    chain_id       BIGINT,
    ntt_count      NUMERIC(56, 12) NOT NULL DEFAULT 1 COMMENT 'NTT',
    gas            NUMERIC(56, 12) NOT NULL DEFAULT 0 COMMENT 'Gas Credit price',
    create_time    datetime COMMENT 'Created time',
    PRIMARY KEY (chain_price_id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT 'Price information';


CREATE TABLE sys_data_center
(
    dc_id               BIGINT       NOT NULL auto_increment COMMENT 'Data Center ID',
    contacts_email      VARCHAR(60)  NOT NULL DEFAULT '' COMMENT 'Email Address',
    ntt_account_address VARCHAR(100) NOT NULL DEFAULT '' COMMENT 'NTT Wallet Address',
    token               VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'Token',
    dc_code             VARCHAR(20)  NOT NULL DEFAULT '' COMMENT 'ID',
    logo                mediumtext COMMENT 'logo',
    create_time         datetime COMMENT 'Created time',
    PRIMARY KEY (dc_id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT 'Data Center Information Table';


CREATE TABLE dc_chain
(
    chain_id         BIGINT       NOT NULL auto_increment,
    chain_type       VARCHAR(50)  NOT NULL DEFAULT '' COMMENT 'Chain Type',
    chain_name       VARCHAR(100) NOT NULL DEFAULT '' COMMENT 'Chain Name',
    recharge_unit    VARCHAR(10)  NOT NULL DEFAULT '' COMMENT 'unit',
    chain_code       varchar(20)  NOT NULL DEFAULT '' COMMENT 'Chain request ID   unique:  After the business system is successfully configured, the gateway needs to be modified',
    gateway_type     smallint(6) NOT NULL DEFAULT '0' COMMENT 'whether support gateway    0: Not supported    1: supported',
    gateway_url      varchar(200) NOT NULL DEFAULT '' COMMENT 'Gateway URL',
    ws_gateway_url   varchar(200) NOT NULL DEFAULT '' COMMENT 'websocketgateway URL',
    grpc_gateway_url varchar(200) NOT NULL DEFAULT '' COMMENT 'Json RPC  0: Not supported 1: Supported',
    json_rpc         smallint(6) NOT NULL DEFAULT '0' COMMENT 'Json RPC  0: Not supported 1: Supported',
    websocket        smallint(6) NOT NULL DEFAULT '0' COMMENT 'WebSocket 0: Not supported 1: Supported',
    grpc             smallint(6) NOT NULL DEFAULT '0' COMMENT 'gRPC 0: Not supported 1: Supported',
    PRIMARY KEY (chain_id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT 'Data Center - Chain Information Table';


CREATE TABLE chain_account_recharge_meta
(
    recharge_meta_id      BIGINT         NOT NULL auto_increment,
    chain_account_address VARCHAR(100) COMMENT 'Wallet Address',
    gas                   NUMERIC(50, 0) NOT NULL DEFAULT 0 COMMENT 'Topped-up Gas Credit',
    deadline              BIGINT         NOT NULL DEFAULT 0 COMMENT 'Transaction Expiration Time',
    sign                  VARCHAR(500)   NOT NULL DEFAULT '' COMMENT 'Signature    Byte value compiled by base64',
    PRIMARY KEY (recharge_meta_id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT 'Emergency Top-up Gas Credit Information Table';


CREATE TABLE dc_gas_recharge_record
(
    recharge_record_id BIGINT       NOT NULL auto_increment,
    chain_id           bigint(20) DEFAULT NULL,
    order_id           bigint(20) DEFAULT NULL,
    chain_address      VARCHAR(100) NOT NULL COMMENT 'Wallet Address',
    gas                NUMERIC(50)  NOT NULL DEFAULT 0,
    recharge_time      datetime              DEFAULT CURRENT_TIMESTAMP COMMENT 'Top-up Time',
    state              SMALLINT     NOT NULL DEFAULT 0 COMMENT 'Top-up submission status   1: Pending    2: In Progress    3: Submitted    4: Failed',
    tx_hash            VARCHAR(200)          DEFAULT NULL COMMENT 'Transaction hash',
    update_time        datetime              DEFAULT NULL COMMENT 'Update time',
    recharge_code      VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'Top-up ID: the event is returned from the chain',
    ntt                NUMERIC(56, 12) COMMENT 'NTT consumed by topping up Gas Credit  Event parsing data',
    recharge_result    VARCHAR(500) COMMENT 'Result:  if success, returns the transaction hash; if failed, returns the reason',
    recharge_state     SMALLINT     NOT NULL DEFAULT 3 COMMENT 'Top-up status   0: In Progress   1: Success    2: Failed  3: No processing required',
    nonce              BIGINT       NOT NULL DEFAULT 0 COMMENT "nonce of emergency Gas Credit top-up, corresponding to the table's primary key",
    md5_sign           VARCHAR(64)           DEFAULT '' COMMENT 'The hash value generated by MD5 algorithm of the data obtained from the parsed block',
    PRIMARY KEY (recharge_record_id)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT 'Gas Credit top-up record table  (End-user Gas Credit top-up + emergency Gas Credit top-up (event parsing))';


CREATE TABLE `dc_node`
(
    `node_id`              BIGINT (20) NOT NULL AUTO_INCREMENT,
    `chain_id`             BIGINT (20) DEFAULT NULL,
    `node_code`            VARCHAR(200) NOT NULL DEFAULT '' COMMENT 'Node ID',
    `rpc_address`          VARCHAR(100) NOT NULL DEFAULT '' COMMENT 'RPC address',
    `node_address`         VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'Node address',
    `apply_sign`           VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'Node registration data signature',
    `state`                SMALLINT (6) NOT NULL DEFAULT '0' COMMENT 'Status  0: Pending   1: Submitted 2: Node registration testing   3: Failed    4: Success',
    `remarks`              VARCHAR(500)          DEFAULT NULL COMMENT 'Remarks',
    `create_time`          datetime     NOT NULL COMMENT 'Date applied',
    `tx_hash`              VARCHAR(100)          DEFAULT NULL COMMENT 'Transaction Hash',
    `tx_time`              datetime              DEFAULT NULL COMMENT 'Transaction time',
    `apply_result_time`    datetime              DEFAULT NULL COMMENT 'Date of notifying the node registration application result',
    `apply_result_tx_hash` VARCHAR(100)          DEFAULT NULL COMMENT 'Transaction hash of the node registration application',
    `ntt_count`            DECIMAL(56, 12)       DEFAULT '0.000000000000' COMMENT 'Amount of NTT Incentives',
    `reason`               VARCHAR(500)          DEFAULT ' ' COMMENT 'Reason',
    PRIMARY KEY (`node_id`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8 COMMENT = 'Full Node Information Table';


CREATE TABLE ntt_tx_sum
(
    `ntt_tx_sum_id` BIGINT (20) NOT NULL AUTO_INCREMENT COMMENT 'ntt_tx_sum_id',
    `flow_in`       DECIMAL(56, 12) NOT NULL DEFAULT '0.000000000000' COMMENT 'in',
    `flow_out`      DECIMAL(56, 12) NOT NULL DEFAULT '0.000000000000' COMMENT 'out',
    PRIMARY KEY (`ntt_tx_sum_id`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8 COMMENT = 'NTT transaction summary';



INSERT INTO `dc_chain` (`chain_id`, `chain_type`, `chain_name`, `recharge_unit`)
VALUES ('1', 'ETH', 'Spartan-I Chain (Powered by NC Ethereum)', 'GWEI'),
       ('2', 'Cosmos', 'Spartan-II Chain (Powered by NC Cosmos)', 'UGAS'),
       ('3', 'Polygon', 'Spartan-III Chain (Powered by NC PolygonEdge)', 'GWEI');



create table dc_payment_order
(
    `order_id`           bigint(20) NOT NULL AUTO_INCREMENT,
    `chain_id`           bigint(20) DEFAULT NULL,
    `sale_price_id`      bigint(20) DEFAULT NULL,
    `payment_type_id`    bigint(20) NOT NULL DEFAULT '0' COMMENT 'Payment method',
    `trade_no`           varchar(50)     NOT NULL DEFAULT '' COMMENT 'Transaction No. (created by the sytem)',
    `other_trade_no`     varchar(50)     NOT NULL DEFAULT '' COMMENT 'Third-party transaction No.',
    `payment_intent`     varchar(50)              DEFAULT '' COMMENT 'payment information',
    `account_address`    varchar(100)    NOT NULL DEFAULT '' COMMENT 'wallet address',
    `email`              varchar(50)     NOT NULL DEFAULT '' COMMENT 'email address',
    `currency`           varchar(20)     NOT NULL DEFAULT '' COMMENT 'Currency type when pay by fiat currency: USD......； when pay by stablecoins: USDC......',
    `ex_rates`           varchar(50)     NOT NULL DEFAULT '' COMMENT 'Gas Credit ratio',
    `gas_count`          decimal(56, 0)  NOT NULL DEFAULT '0' COMMENT 'Amount of Gas Credit',
    `pay_account`        varchar(100)    NOT NULL DEFAULT '' COMMENT 'Address for payment',
    `pay_amount`         decimal(56, 12) NOT NULL DEFAULT '0.000000000000' COMMENT 'Payment amount',
    `pay_state`          smallint(6) NOT NULL DEFAULT '0' COMMENT 'Payment status     0: payment in progress   1: payment successful 2: payment failed',
    `pay_time`           datetime                 DEFAULT NULL COMMENT 'Payment time',
    `tx_hash`            varchar(100)    NOT NULL DEFAULT '' COMMENT 'Transaction hash',
    `tx_time`            datetime                 DEFAULT NULL COMMENT 'Transaction time',
    `gas_tx_hash`        varchar(100)    NOT NULL DEFAULT '' COMMENT 'Gas Credit top-up transaction hash',
	`gas_tx_time`        datetime        DEFAULT NULL COMMENT 'Gas Credit top-up time',
    `gas_recharge_state` smallint(6) NOT NULL DEFAULT '3' COMMENT 'Top-up status     0: Top-up in progress   1: Top-up successful 2: Top-up failed   3: Pending',
    `is_refund`          smallint(6) NOT NULL DEFAULT '0' COMMENT 'Refund 0: Not refunded 1: Refunded',
    `refund_amount`      decimal(56, 12) NOT NULL DEFAULT '0.000000000000' COMMENT 'Refund amount',
    `remarks`            varchar(200)    NOT NULL DEFAULT '' COMMENT 'Remarks',
    `update_time`        datetime        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Update time',
    `create_time`        datetime        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    primary key (order_id)
) ENGINE = INNODB
  DEFAULT CHARSET = utf8 comment  'Gas payment order table';


create table dc_payment_refund
(
    refund_id       bigint          not null auto_increment,
    order_id        bigint,
    trade_no        varchar(50)     not null default '' comment 'Transaction No. (created by the sytem)',
    other_trade_no  varchar(50)     not null default '' comment 'Third-party transaction No.',
    account_address varchar(100)    not null default '' comment 'wallet address',
    refund_amount   decimal(56, 12) not null default 0 comment 'Refund amount',
    refund_state    smallint        not null default 0 comment 'Refund status     0: Refund in progress   1: Refund successful 2: Refund failed',
    refund_time     datetime comment 'Refund time',
    remarks         varchar(200)    not null default '' comment 'Remarks',
    refund_receipt  varchar(200)             DEFAULT '' COMMENT 'Refund receipt',
    operator        bigint          not null default 0 comment 'Operator',
    update_time     datetime        not null default CURRENT_TIMESTAMP comment 'Update time',
    create_time     datetime        not null default CURRENT_TIMESTAMP comment 'Created time',
    primary key (refund_id)
) ENGINE = INNODB
  DEFAULT CHARSET = utf8 comment  'GAS refund table';


create table dc_payment_type
(
    payment_type_id  bigint       not null auto_increment,
    pay_type         smallint     not null default 0 comment 'Payment type 1: Fiat currency 2: stablecoins   3: remittance',
    pay_channel_name varchar(50)  not null default '' comment 'Payment channel    stripe 、coinbase',
    channel_code     varchar(10)  not null default '' comment 'channel ID',
    private_key      varchar(300) not null default '' comment 'Private key',
    endpoint_secret  varchar(100) not null default '' comment 'Callback signature key',
    api_key          varchar(50)  not null default '' comment 'api_key',
    api_version      varchar(20)  not null default '' comment 'api_version',
    bank_name        varchar(50)  not null default '' comment 'Bank name',
    bank_account     varchar(50)  not null default '' comment 'Bank account',
    bank_address     varchar(50)  not null default '' comment 'Bank address',
    swift_code       varchar(50)  not null default '' comment 'swift code',
    enable_status    smallint(1) not null default 1 comment 'Enablement status 0:enabled 1:disabled',
    create_time      datetime     not null default CURRENT_TIMESTAMP comment 'Created time',
    update_time      datetime     not null default CURRENT_TIMESTAMP comment 'Update time',
    primary key (payment_type_id)
) ENGINE = INNODB
  DEFAULT CHARSET = utf8 comment  'Payment method table';


create table dc_system_conf
(
    conf_id     bigint        not null auto_increment,
    type        smallint      not null default 1 comment 'Type   1: Portal information   2: Technical support 3: contact us   4: chain access information 5: Keystore  6: Treaty',
    conf_code   varchar(50)   not null default '' comment 'conf_code',
    conf_value  mediumtext default null comment 'conf_value',
    update_time datetime comment 'Update time',
    primary key (conf_id)
) ENGINE = INNODB
  DEFAULT CHARSET = utf8 comment  'Configuration information table';


create table chain_sale_price
(
    sale_price_id  bigint       not null auto_increment,
    chain_price_id bigint,
    chain_id       bigint,
    gas            decimal(56)  not null default 1 comment 'Gas Credit amount',
    sale_price     decimal(56)  not null default 0 comment 'Gas Credit Price (USD cent)',
    state          smallint     not null default 0 comment 'Status 1: pending review 2: approved 3: not approved',
    start_time     datetime comment 'Effective date',
    end_time       datetime comment 'Expiry date',
    create_user_id bigint       not null default 0 comment 'Created by',
    create_time    datetime     not null default CURRENT_TIMESTAMP comment 'Created time',
    check_user_id  bigint       not null default 0 comment 'Reviewed by',
    check_time     datetime     not null default CURRENT_TIMESTAMP comment 'Review time',
    check_remark   varchar(200) not null default "" comment 'Comment',
    primary key (sale_price_id)
) ENGINE = INNODB
  DEFAULT CHARSET = utf8 comment  'Price information table';


create table dc_chain_access
(
    chain_access_id    bigint      not null auto_increment,
    access_key         varchar(32) not null comment 'Access key   UUID',
    contacts_email     varchar(60) not null default '' comment 'email address',
    state              smallint             default 1 comment 'Status    1:enabled(default)，2 disabled，3 deleted',
    tps                int         not null default -1 comment 'TPS  -1 means no limits',
    tpd                int         not null default -1 comment 'TPD  -1 means no limits',
    stripe_customer_id varchar(50) not null default '' comment 'Stripe user id',
    create_time        datetime    not null default CURRENT_TIMESTAMP comment 'Created time',
    update_time        datetime    not null default CURRENT_TIMESTAMP comment 'Update time',
    notify_state       smallint             default 1 comment 'Notify Gateway Status 1: success 2: failed',
    primary key (chain_access_id)
) ENGINE = INNODB
  DEFAULT CHARSET = utf8 comment  'User access record table';


CREATE TABLE `sys_message_template`
(
    `template_id` bigint(20) NOT NULL AUTO_INCREMENT,
    `msg_code`    varchar(50)   NOT NULL DEFAULT '' COMMENT 'Template ID',
    `msg_title`   varchar(100)           DEFAULT NULL COMMENT 'Template title',
    `msg_content` varchar(2000) NOT NULL DEFAULT '' COMMENT 'Template content',
    `msg_type`    smallint(6) NOT NULL DEFAULT '0' COMMENT 'Message type    1: Station letter 2: email  ',
    `update_time` datetime      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Update time',
    `create_time` datetime      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    `state`       smallint(6) NOT NULL DEFAULT '1' COMMENT 'Status，1: enabled       0: disabled',
    PRIMARY KEY (`template_id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8 COMMENT='Email template table';


CREATE TABLE `sys_mail_record`
(
    `record_id`    bigint(20) NOT NULL AUTO_INCREMENT,
    `template_id`  bigint(20) DEFAULT NULL,
    `sender`       varchar(50)   NOT NULL DEFAULT '' COMMENT 'Sender',
    `receiver`     varchar(200)  NOT NULL DEFAULT '' COMMENT 'Recipient',
    `cc_people`    varchar(200)           DEFAULT NULL COMMENT 'CC',
    `mail_title`   varchar(200)  NOT NULL DEFAULT '' COMMENT 'Email title',
    `mail_content` varchar(1000) NOT NULL DEFAULT '' COMMENT 'Email content',
    `state`        smallint(6) NOT NULL DEFAULT '1' COMMENT 'Sending Status，1: successful 0: failed',
    `send_time`    datetime      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Send time',
    PRIMARY KEY (`record_id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8 COMMENT='Send email record table';
  
CREATE TABLE `sys_role` (
                            `role_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'Role id',
                            `role_code` varchar(20) NOT NULL DEFAULT '' COMMENT 'Role code',
                            `role_name` varchar(20) NOT NULL DEFAULT '' COMMENT 'Role name',
                            `description` varchar(500) DEFAULT '' COMMENT 'Description',
                            `create_user` bigint(20) NOT NULL,
                            `create_date` datetime NOT NULL COMMENT 'Created time',
                            `update_user` bigint(20) DEFAULT NULL COMMENT 'Modified by',
                            `update_date` datetime DEFAULT NULL COMMENT 'Update time',
                            `state` smallint(6) NOT NULL DEFAULT '0' COMMENT 'Status   1: Enabled   2: Disabled',
                            PRIMARY KEY (`role_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='Role table';


CREATE TABLE `sys_user_role` (
                                 `user_role_id` bigint(20) NOT NULL AUTO_INCREMENT,
                                 `user_id` bigint(20) DEFAULT NULL,
                                 `role_id` bigint(20) DEFAULT NULL,
                                 PRIMARY KEY (`user_role_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='User role table';

CREATE TABLE `sys_resource` (
                                `rsuc_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'Resource id',
                                `parent_id` bigint(20) NOT NULL DEFAULT '0' COMMENT 'Parent number',
                                `rsuc_code` varchar(50) NOT NULL DEFAULT '' COMMENT 'Resource code',
                                `rsuc_name` varchar(50) NOT NULL DEFAULT '' COMMENT 'Resource name',
                                `rsuc_url` varchar(150) NOT NULL DEFAULT '' COMMENT 'Resource path',
                                `priority` int(11) NOT NULL DEFAULT '0' COMMENT 'Sequence',
                                `rsuc_type` smallint(6) NOT NULL DEFAULT '1' COMMENT 'Permission Category 1: Page 2: Button',
                                `state` smallint(6) NOT NULL DEFAULT '1' COMMENT 'Status   1: Enabled   2: Disabled',
                                PRIMARY KEY (`rsuc_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='Resource table';


CREATE TABLE `sys_role_resource` (
                                     `role_resource_id` bigint(20) NOT NULL AUTO_INCREMENT,
                                     `role_id` bigint(20) DEFAULT NULL,
                                     `rsuc_id` bigint(20) DEFAULT NULL,
                                     PRIMARY KEY (`role_resource_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='Role resource table';


INSERT INTO `dc_system_conf` (`type`, `conf_code`, `conf_value`, `update_time`)
VALUES (1, 'title', 'BSN Spartan Network Data Center Portal', now());
INSERT INTO `dc_system_conf` (`type`, `conf_code`, `conf_value`, `update_time`)
VALUES (1, 'headline', 'BSN Spartan Network Data Center Portal', now());
INSERT INTO `dc_system_conf` (`type`, `conf_code`, `conf_value`, `update_time`)
VALUES (1, 'introduce',
        'BSN Spartan Data Center is a lightweight software platform that provides access to the Spartan Network. In the data center, the operator can install and access nodes of the public chain, the mission of the Spartan. By removing cryptocurrency from the first layer of the public chain, the mission of the Spartan Network is to provide all IT systems around the world with non-cryptocurrency public chain services, so as to to gain the benefits of a public IT infrastructure.',
        now());
INSERT INTO `dc_system_conf` (`type`, `conf_code`, `conf_value`, `update_time`)
VALUES (1, 'copyright', '', now());
INSERT INTO `dc_system_conf` (`type`, `conf_code`, `conf_value`, `update_time`)
VALUES (2, 'Telegram', 'https://t.me/bsnsupport', now());
INSERT INTO `dc_system_conf` (`type`, `conf_code`, `conf_value`, `update_time`)
VALUES (2, 'Whatsapp', 'https://chat.whatsapp.com/H9wENt0lw4dFTVopaILFxh', now());
INSERT INTO `dc_system_conf` (`type`, `conf_code`, `conf_value`, `update_time`)
VALUES (2, 'Reddit', 'https://www.reddit.com/r/BSNSpartanSupport/', now());
INSERT INTO `dc_system_conf` (`type`, `conf_code`, `conf_value`, `update_time`)
VALUES (2, 'Discord', 'https://discord.gg/HEpnKTUyAX', now());
INSERT INTO `dc_system_conf` (`type`, `conf_code`, `conf_value`, `update_time`)
VALUES (2, 'Twitter', 'https://twitter.com/bsnbase', now());
INSERT INTO `dc_system_conf` (`type`, `conf_code`, `conf_value`, `update_time`)
VALUES (3, 'address', '36/F, PCCW Tower, Taikoo Place, 979 King’s Road, Quarry Bay, HK', now());
INSERT INTO `dc_system_conf` (`type`, `conf_code`, `conf_value`, `update_time`)
VALUES (3, 'email', 'BSN_Spartan@reddatetech.com.hk', now());
INSERT INTO `dc_system_conf` (`type`, `conf_code`, `conf_value`, `update_time`)
VALUES (3, 'phone', '+852 3978-1407  (UTC+8:00) 9:00 am to 5:00 pm (Mon–Fri)', now());
INSERT INTO `dc_system_conf` (`type`, `conf_code`, `conf_value`, `update_time`)
VALUES (4, 'tps', '', now());
INSERT INTO `dc_system_conf` (`type`, `conf_code`, `conf_value`, `update_time`)
VALUES (4, 'tpd', '', now());
INSERT INTO `dc_system_conf` (`type`, `conf_code`, `conf_value`, `update_time`) 
VALUES (6, 'treaty','<p style="text-align: center;"><strong>TERMS OF SERVICE</strong></p><p><span style="color: rgb(0, 0, 0);">This Terms of Service for Registration as an End User of BSN Spartan Data Center (this “Agreement”) contains the terms and conditions that govern your access to and use of the BSN Spartan Data Center and is an agreement between the Spartan Data Center (also referred to as “we,” “us,” or “our”) and you or the entity you represent (“you” or “your”). This Agreement takes effect when you click an “Accept” or “Agree” button or check box presented with this Agreement or, if earlier, when you use any of the BSN Spartan Data Center. You represent to us that you are lawfully able to enter into contracts (e.g., you are not a minor). If you are entering into this Agreement for an entity, such as the company you work for, you represent to us that you have legal authority to bind that entity. Please see Section 11 for definitions of certain capitalized terms used in this Agreement</span></p><p><strong>1. ABOUT THIS AGREEMENT</strong></p><p><span style="color: rgb(0, 0, 0);">1.1 The BSN Spartan Network is a decentralized cloud service network. The BSN Spartan Network is intended to be co-governed by members of the BSN Foundation (in preparation).</span></p><p><span style="color: rgb(0, 0, 0);">1.2 A Spartan Data Center is a software system that contains one or more registered full nodes of different non-cryptocurrency public chains on the BSN Spartan Network.</span></p><p><span style="color: rgb(0, 0, 0);">1.3 By registering as an End User of Spartan Data Center, you are agreeing to be bound by the terms and conditions of this Agreement.</span></p><p><strong>2. ACCEPTANCE OF THIS AGREEMENT</strong></p><p><span style="color: rgb(0, 0, 0);">2.1 You shall ensure that you have the right to legally use the BSN Spartan Network and that you comply with all applicable laws, regulations, and policies. You will ensure that your use of the BSN Spartan Network will not violate any applicable law. </span></p><p><span style="color: rgb(0, 0, 0);">2.2 You cannot accept this Agreement if you are under legal age.</span></p><p><strong>3. USE OF THE BSN SPARTAN NETWORK</strong></p><p><span style="color: rgb(0, 0, 0);">3.1 Subject to this Agreement, you may register as an End User of BSN Spartan Data Center on an anonymous basis.</span></p><p><span style="color: rgb(0, 0, 0);">3.2 You shall comply with the Spartan License of the Software and be fully and solely responsible for the operation, maintenance and data security of the localized system, including but not limited to, any third-party software, applications, and tools you choose to install, as well as the security of your local system, data, and hardware.</span></p><p><span style="color: rgb(0, 0, 0);">3.3 If we become aware of any violation of your obligations under this Agreement caused by an End User, we will immediately suspend access to the BSN Spartan Network by such End User.</span></p><p><span style="color: rgb(0, 0, 0);">3.4 You shall comply with all rules, regulations and terms of the BSN Spartan Data Center as published on the Website from time to time.</span></p><p><span style="color: rgb(0, 0, 0);">3.5 We do not collect any identifying information about you other than your email address. Please check your emails frequently and always make the email account available to receive emails, as we may send you important notifications such as security patches and software updates. We are not responsible for any system problems or losses that may occur due to non-receipt of such notifications due to incorrect/inactive email address.</span></p><p><span style="color: rgb(0, 0, 0);">3.6 You must not:</span></p><p><span style="color: rgb(0, 0, 0);">(a) use any type of spider, virus, worm, Trojan horse, time bomb or any other codes or instructions designed to distort, remove, damage, simulate or disassemble the BSN Spartan Network; or</span></p><p><span style="color: rgb(0, 0, 0);">(b) send unsolicited communications (also referred to as ‘SPAM’, ‘SPIM’ or ‘SPIT’) or any communications not permitted by applicable law or phishing or pharming using the BSN Spartan Network, or impersonating or misrepresenting affiliation with another person or entity; or</span></p><p><span style="color: rgb(0, 0, 0);">(c) expose any third party to material which is offensive, harmful to minors, indecent or otherwise objectionable in any way; or</span></p><p><span style="color: rgb(0, 0, 0);">(d) use the BSN Spartan Network to cause or intend to cause embarrassment or distress to any third party, or to threaten, harass or invade the privacy of any third party; or</span></p><p><span style="color: rgb(0, 0, 0);">(e) use any material or content that is subject to any proprietary rights of any third party, unless you obtain a license or permission from the owner of such rights; or</span></p><p><span style="color: rgb(0, 0, 0);">(f) collect or obtain any personally identifiable information, including account names, from the BSN Spartan Network; or</span></p><p><span style="color: rgb(0, 0, 0);">(g) impact or attempt to impact the availability of the BSN Spartan Network, for example, with a denial of service (DOS) or distributed denial of service (DDoS) attack; or</span></p><p><span style="color: rgb(0, 0, 0);">(h) use or launch any automated system, including but not limited to, robots, spiders or offline readers that access the BSN Spartan Network.</span></p><p><strong>4. FEES AND PAYMENT</strong></p><p><span style="color: rgb(0, 0, 0);">4.1 You will pay us the applicable fees and charges for use of the BSN Spartan Data Center as described on the Website using one of the payment methods we support. All amounts payable by you under this Agreement will be paid to us without setoff or counterclaim, and without any deduction or withholding. Fees and charges for use of the BSN Spartan Data Center will be effective when we post updated fees and charges on the Website, unless we expressly state otherwise in a notice. We may increase or add new fees and charges by giving you at least 30 days’ prior notice.</span></p><p><span style="color: rgb(0, 0, 0);">4.2 Each party will be responsible, as required under applicable law, for identifying and paying all taxes and other governmental fees and charges (and any penalties, interest, and other additions thereto) that are imposed on that party upon or with respect to the transactions and payments under this Agreement. All fees payable by you are exclusive of Taxes, except where applicable law requires otherwise. We may charge and you will pay applicable Taxes that we are legally obligated or authorized to collect from you. You will provide such information to us as reasonably required to determine whether we are obligated to collect Taxes from you. We will not collect, and you will not pay, any Tax for which you furnish us a properly completed exemption certificate or a direct payment permit certificate for which we may claim an available exemption from such Tax. All payments made by you to us under this Agreement will be made free and clear of any deduction or withholding, as may be required by law. If any such deduction or withholding (including but not limited to cross-border withholding taxes) is required on any payment, you will pay such additional amounts as are necessary so that the net amount received by us is equal to the amount then due and payable under this Agreement. We will provide you with such tax forms as are reasonably requested in order to reduce or eliminate the amount of any withholding or deduction for taxes in respect of payments made under this Agreement.</span></p><p><strong>5. INDEMNIFICATION</strong></p><p><span style="color: rgb(0, 0, 0);">5.1 You will defend, indemnify, and hold harmless us, our affiliates and licensors, and each of their respective employees, officers, directors, and representatives from and against any Losses arising out of or relating to any third-party claim concerning: (a) your use of the BSN Spartan Data Center (including any activities under your account and use by your employees and personnel); (b) breach of this Agreement or violation of applicable law by you. You will reimburse us for reasonable attorneys’ fees, as well as our employees’ and contractors’ time and materials spent responding to any third party subpoena or other compulsory legal order or process associated with third party claims described in (a) through (c) above at our then-current hourly rates.</span></p><p><span style="color: rgb(0, 0, 0);">5.2 The obligations under this Section 5 will apply only if the party seeking defense or indemnity: (a) gives the other party prompt written notice of the claim; (b) permits the other party to control the defense and settlement of the claim; and (c) reasonably cooperates with the other party (at the other party’s expense) in the defense and settlement of the claim. In no event will a party agree to any settlement of any claim that involves any commitment, other than the payment of money, without the written consent of the other party.</span></p><p><strong>6. DISCLAIMER</strong></p><p><span style="color: rgb(0, 0, 0);">EXCEPT AS EXPRESSLY PROVIDED FOR IN THIS AGREEMENT, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW: (A) WE AND OUR AFFILIATES DO NOT MAKE ANY OTHER WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR USE, NONINFRINGEMENT OR QUIET ENJOYMENT; (B) WE AND OUR AFFILIATES ARE NOT RESPONSIBLE OR LIABLE FOR THE DELETION OF OR FAILURE TO STORE ANY YOUR DATA AND OTHER COMMUNICATIONS MAINTAINED OR TRANSMITTED THROUGH USE OF THE SOFTWARE OR THE BSN SPARTAN NETWORK; (C) YOU ARE SOLELY RESPONSIBLE FOR SECURING AND BACKING UP ITS APPLICATION, PROJECT, AND DATA; AND (D) NEITHER WE NOR OUR AFFILIATE WARRANTS THAT THE OPERATION OF THE SOFTWARE OR THE BSN SPARTAN NETWORK WILL BE ERROR-FREE OR UNINTERRUPTED OR FREE OF HARMFUL COMPONENTS OR THAT ANY CONTENT WILL BE SECURE OR NOT OTHERWISE LOST OR ALTERD. NEITHER THE BSN SPARTAN NETWORK NOR THE SPARTAN DATA CENTER ARE DESIGNED, MANUFACTURED, OR INTENDED FOR HIGH RISK ACTIVITIES.</span></p><p><strong>7. PRIVACY</strong></p><p><span style="color: rgb(0, 0, 0);">We will not collect your private data. You are fully and solely responsible for the confidentiality of your private data in your local systems and on the non-cryptocurrency public chains on the BSN Spartan Network.</span></p><p><strong>8. LIMITATION OF LIABILITY</strong></p><p><span style="color: rgb(0, 0, 0);">WE AND OUR AFFILIATES WILL NOT BE LIABLE TO YOU FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES (INCLUDING DAMAGES FOR LOSS OF PROFITS, REVENUES, CUSTOMERS, OPPORTUNITIES, GOODWILL, USE, OR DATA), EVEN IF A PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. FURTHER, NEITHER WE NOR ANY OF OUR AFFILIATES OR LICENSORS WILL BE RESPONSIBLE FOR ANY COMPENSATION, REIMBURSEMENT, OR DAMAGES ARISING IN CONNECTION WITH: (A) YOUR INABILITY TO USE THE BSN SPARTAN NETWORK, INCLUDING AS A RESULT OF ANY (I) TERMINATION OR SUSPENSION OF THIS AGREEMENT OR YOUR USE OF OR ACCESS TO THE BSN SPARTAN NETWORK, (II) OUR DISCONTINUATION OF ANY OR ALL OF THE SERVICE OFFERINGS OF THE BSN SPARTAN NETWORK, OR, (III) ANY UNANTICIPATED OR UNSCHEDULED DOWNTIME OF ALL OR A PORTION OF THE BSN SPARTAN NETWORK FOR ANY REASON; (B) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; (C) ANY INVESTMENTS, EXPENDITURES, OR COMMITMENTS BY YOU IN CONNECTION WITH THIS AGREEMENT OR YOUR USE OF OR ACCESS TO THE BSN SPARTAN NETWORK; OR (D) ANY UNAUTHORIZED ACCESS TO, ALTERATION OF, OR THE DELETION, DESTRUCTION, DAMAGE, LOSS OR FAILURE TO STORE ANY OF YOUR CONTENT OR OTHER DATA. IN ANY CASE, OUR AND OUR AFFILIATES’ AND LICENSORS’ AGGREGATE LIABILITY UNDER THIS AGREEMENT WILL NOT EXCEED THE AMOUNT YOU ACTUALLY PAY US UNDER THIS AGREEMENT FOR THE SERVICE THAT GAVE RISE TO THE CLAIM DURING THE 1 MONTH BEFORE THE LIABILITY AROSE, NOT EXCEEDING A TOTAL OF </span><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 0);">[*]</span><span style="color: rgb(0, 0, 0);"> US DOLLARS. THE LIMITATIONS IN THIS SECTION 8 APPLY ONLY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW.</span></p><p><strong>9. MODIFICATIONS TO THIS AGREEMENT</strong></p><p><span style="color: rgb(0, 0, 0);">We may modify this Agreement at any time by posting a revised version on the Website or by otherwise notifying you in accordance with Section 10.7. The modified terms will become effective upon posting or, if we notify you by email, as stated in the email message. By continuing to use the BSN Spartan Data Center after the effective date of any modifications to this Agreement, you agree to be bound by the modified terms. It is your responsibility to check the Website regularly for modifications to this Agreement. We last modified this Agreement on the date indicated on the Website.</span></p><p><strong>10. MISCELLANEOUS</strong></p><p><span style="color: rgb(0, 0, 0);">10.1 Assignment. We may assign this Agreement without your consent. Subject to the foregoing, this Agreement will be binding upon, and inure to the benefit of the parties and their respective permitted successors and assigns.</span></p><p><span style="color: rgb(0, 0, 0);">10.2 Entire Agreement. This Agreement is the entire agreement between you and us regarding the subject matter of this Agreement. This Agreement supersedes all prior or contemporaneous representations, understandings, agreements, or communications between you and us, whether written or verbal, regarding the subject matter of this Agreement.</span></p><p><span style="color: rgb(0, 0, 0);">10.3 No Partnership or Agency. Nothing in this agreement is intended to, or shall be deemed to, establish any partnership or joint authorise venture between any of the parties, constitute any party the agent of another party, or any party to make or enter into any commitments for or on behalf of any other party.</span></p><p><span style="color: rgb(0, 0, 0);">10.4 Governing Law. This agreement will be governed by and construed in accordance with the laws of </span><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 0);">[*]</span><span style="color: rgb(0, 0, 0);">.</span></p><p><span style="color: rgb(0, 0, 0);">10.5 Dispute Resolution.</span></p><p><span style="color: rgb(0, 0, 0);">(a) In the event of any dispute, controversy, difference or claim arising from or in connection with this agreement including the existence, validity, interpretation, performance, breach or termination thereof or any dispute regarding non-contractual obligations arising out of or relating to it, the parties shall first use best endeavours to resolve such dispute, controversy, difference or claim amicably.</span></p><p><span style="color: rgb(0, 0, 0);">(b) If resolution cannot be reached within thirty (30) calendar days, any dispute or claim arising out of or relating to this agreement shall be referred to and finally resolved by arbitration administered by the </span><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 0);">[*]</span><span style="color: rgb(0, 0, 0);"> under the </span><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 0);">[*]</span><span style="color: rgb(0, 0, 0);"> in force when the Notice of Arbitration is submitted. The law of this arbitration clause shall be </span><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 0);">[*]</span><span style="color: rgb(0, 0, 0);">. The seat of arbitration shall be </span><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 0);">[*]</span><span style="color: rgb(0, 0, 0);">. The number of arbitrators shall be </span><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 0);">[*]</span><span style="color: rgb(0, 0, 0);">. The arbitration proceedings shall be conducted in English.</span></p><p><span style="color: rgb(0, 0, 0);">(c) Notwithstanding anything to the contrary contained in this agreement, and without limiting any rights of either party under this agreement, either party has the right to seek any preliminary injunction or other equitable relief in any court of competent jurisdiction to enforce that party’s rights hereunder.</span></p><p><span style="color: rgb(0, 0, 0);">10.6 Language. All communications and notices made or given pursuant to this Agreement must be in the English language. If we provide a translation of the English language version of this Agreement, the English language version of this Agreement will control if there is any conflict.</span></p><p><span style="color: rgb(0, 0, 0);">10.7 Notice.</span></p><p><span style="color: rgb(0, 0, 0);">(a) To You. We may provide any notice to you under this Agreement by: (i) posting a notice on the Website; or (ii) sending a message to the email address then associated with your account. Notices we provide by posting on the Website will be effective upon posting and notices we provide by email will be effective when we send the email. It is your responsibility to keep your email address current. You will be deemed to have received any email sent to the email address then associated with your account when we send the email, whether or not you actually receive the email.</span></p><p><span style="color: rgb(0, 0, 0);">(b) To Us. To give us notice under this Agreement, you must contact us by sending a message to the email: </span><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 0);">[*]</span></p><p><span style="color: rgb(0, 0, 0);">10.8 No Third-Party Beneficiaries. Except as set forth in Section 5, this Agreement does not create any third-party beneficiary rights in any individual or entity that is not a party to this Agreement.</span></p><p><strong>11. DEFINITIONS</strong></p><p><span style="color: rgb(0, 0, 0);">“End User” means any individual or entity that directly or indirectly accesses or uses the BSN Spartan Network via BSN Spartan Data Center.</span></p><p><span style="color: rgb(0, 0, 0);">“Losses” means any claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys’ fees).</span></p><p><span style="color: rgb(0, 0, 0);">“Software” means the data center software for the BSN Spartan Network made available under the Spartan License.</span></p><p><span style="color: rgb(0, 0, 0);">“Spartan License” means the terms and conditions for use, reproduction, and distribution as published by Red Date at https://spartan.bsn.foundation/licenses/license.</span></p><p><span style="color: rgb(0, 0, 0);">“Taxes” means applicable taxes and duties, including, without limitation, VAT, service tax, GST, excise taxes, sales and transactions taxes, and gross receipts tax.</span></p><p><span style="color: rgb(0, 0, 0);">“Website” means https: </span><span style="color: rgb(0, 0, 0); background-color: rgb(255, 255, 0);">[*]</span><span style="color: rgb(0, 0, 0);"> (and any successor or related locations designated by us), as may be updated by us from time to time.</span></p>', now());



INSERT INTO `dc_payment_type` (`pay_type`, `pay_channel_name`, `channel_code`, `private_key`, `endpoint_secret`,
                               `api_key`, `api_version`, `bank_name`, `bank_account`, `bank_address`, `swift_code`,
                               `enable_status`, `create_time`, `update_time`)
VALUES (1, 'Stripe', 'STRIPE', '', '', '', '', '', '', '', '', 1, now(), now());
INSERT INTO `dc_payment_type` (`pay_type`, `pay_channel_name`, `channel_code`, `private_key`, `endpoint_secret`,
                               `api_key`, `api_version`, `bank_name`, `bank_account`, `bank_address`, `swift_code`,
                               `enable_status`, `create_time`, `update_time`)
VALUES (2, 'Coinbase', 'COINBASE', '', '', '', '', '', '', '', '', 1, now(), now());
INSERT INTO `dc_payment_type` (`pay_type`, `pay_channel_name`, `channel_code`, `private_key`, `endpoint_secret`,
                               `api_key`, `api_version`, `bank_name`, `bank_account`, `bank_address`, `swift_code`,
                               `enable_status`, `create_time`, `update_time`)
VALUES (3, 'Remittance', 'OFFLINE', '', '', '', '', '', '', '', '', 1, now(), now());


INSERT INTO `sys_message_template` (now()`msg_code`, `msg_title`, `msg_content`, `msg_type`, `update_time`, `create_time`, `state`) VALUES ('email_template', 'Email template', '<blockquote style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0.5em;\"><div><div><table align=\"center\" cellspacing=\"0\" cellpadding=\"0\" style=\"width: 700px;border: 1px solid #9B9B9B;\"><tbody><tr><td style=\"background-color:#013893;height:60px;\"><img src=\"${logo}\" style=\"margin:10px; height:36px;\"></td></tr><tr><td><table width=\"700\" style=\"padding-left: 24px;padding-right: 24px;\"><tbody><tr><td style=\"padding-top: 18px; font-size: 14px; color: #000000;\"><span>Hello there,</span></td></tr><tr><td style=\"padding-top: 24px; font-size: 14px; color: #000000;word-break:break-word;overflow: hidden;\"><span style=\"line-height:200%;\">${text}</span></td></tr>${contact}</tbody></table></td></tr></tbody></table><p style=\"text-align: center;font-size: 12px;line-height: 20px;color: #4A4A4A;\">This email is automatically sent by the system, please do not reply, and if you are not using BSN Spartan Network, please ignore.</p></div></div></blockquote>', 2, now(), now(), 1);
INSERT INTO `sys_message_template` (now()`msg_code`, `msg_title`, `msg_content`, `msg_type`, `update_time`, `create_time`, `state`) VALUES ('contact_template_', 'Contact information email template', '<tr><td style=\"font-size: 14px; color: #000000;padding-top: 15px;padding-bottom: 15px;\"><span>Thank you for using BSN Spartan Network!</span></td></tr><tr><td style=\"font-size: 14px; color: #000000;\"><span>If you have any questions, please contact us by the following ways:</span></td></tr><tr><td style=\"font-size: 14px; padding-top: 5px;\">-Telegram:&nbsp;<a target=\"_blank\" href=\"https://t.me/bsnsupport\">https://t.me/bsnsupport</a></td></tr><tr><td style=\"font-size: 14px; padding-top: 5px;\">-Whatsapp:&nbsp;<a target=\"_blank\" href=\"https://chat.whatsapp.com/H9wENt0lw4dFTVopaILFxh\">https://chat.whatsapp.com/H9wENt0lw4dFTVopaILFxh</td></tr><tr><td style=\"font-size: 14px; padding-top: 5px;\">-Reddit:&nbsp;<a target=\"_blank\" href=\"https://www.reddit.com/r/BSNSpartanSupport/\">https://www.reddit.com/r/BSNSpartanSupport/</a></td></tr><tr><td style=\"font-size: 14px; padding-top: 5px;\">-Discord:&nbsp;<a target=\"_blank\" href=\"https://discord.gg/HEpnKTUyAX\">https://discord.gg/HEpnKTUyAX</a></td></tr><tr><td style=\"font-size: 14px; padding-top: 5px;\">-Email:&nbsp;<a href=\"mailto:BSN_Spartan_support@reddatetech.com.hk\">BSN_Spartan_support@reddatetech.com.hk</td></tr><tr><td>&nbsp;</td></tr>', 2, now(), now(), 1);
INSERT INTO `sys_message_template` (now()`msg_code`, `msg_title`, `msg_content`, `msg_type`, `update_time`, `create_time`, `state`) VALUES ('user_join_captcha_', 'BSN Spartan Data Center Notification: <b>${captcha_}</b> is your verification code', 'Thank you for accessing the BSN Spartan Network!<br/><b>${captcha_}</b> is your verification code. This code is only valid for ${minutes_} minutes and will no longer be valid if you request a new code.', 2, now(), now(), 1);
INSERT INTO `sys_message_template` (now()`msg_code`, `msg_title`, `msg_content`, `msg_type`, `update_time`, `create_time`, `state`) VALUES ('gas_recharge_captcha_', 'BSN Spartan Data Center Notification: <b>${captcha_}</b> is your verification code', 'Thank you for choosing the BSN Spartan Network!<br/><b>${captcha_}</b> is your verification code. This code is only valid for ${minutes_} minutes and will no longer be valid if you request a new code.', 2, now(), now(), 1);
INSERT INTO `sys_message_template` (now()`msg_code`, `msg_title`, `msg_content`, `msg_type`, `update_time`, `create_time`, `state`) VALUES ('user_join_email_', 'BSN Spartan Data Center Notification: Network Access Information', 'Welcome to the BSN Spartan Network!<br/>You can access the BSN Spartan Network via these nodes:<br/><br/>Spartan-I(Powered by NC Ethereum)<br/>Access Key:${accessKey_}<br/>Access Url Example:${accessDemo_}<br/>Json RPC Access URL:${ethRpc_}<br/>WebSocket Access URL:${ethWs_}<br/><br/>Spartan-II(Powered by NC Cosmos)<br/>Access Key:${accessKey_}<br/>Json RPC:<br/>EVM module:${cosmosEvmRpc_}<br/>Native module:${cosmosRpc_}<br/>WebSocket:<br/>EVM module:${cosmosEvmWs_}<br/>Native module:${cosmosWs_}<br/>gRPC:${cosmosGrpc_}<br/><br/>Spartan-III(Powered by NC PolygonEdge)Access Key:${accessKey_}<br/>Json RPC Access URL:${poloygonRpc_}<br/>WebSocket Access URL:${polygonWs_}<br/><br/>', 2, now(), now(), 1);
INSERT INTO `sys_message_template` (now()`msg_code`, `msg_title`, `msg_content`, `msg_type`, `update_time`, `create_time`, `state`) VALUES ('order_submit_offline_', 'BSN Spartan Data Center Notification: Order Submitted', 'We are pleased to inform you that we have received your order. Please complete the payment.<br>Your order information is as follows:<br>Order Number:${trade_no_}<br>Wallet:${account_address_}<br>Gas Credit Amount:${gas_count_}<br>Order Total:US$ ${pay_amount_}<br>Payment Information:<br>Bank Name: ${bank_name_}<br>Bank Account No.: ${bank_account_no_}<br>Bank Address: ${bank_address_}<br>Swift Code: ${swift_code_}<br>Payment Details: ${payment_details_}<br>Note: Please enter the order number in Payment Details so we can top up your Gas Credits', 2, now(), now(), 1);
INSERT INTO `sys_message_template` (now()`msg_code`, `msg_title`, `msg_content`, `msg_type`, `update_time`, `create_time`, `state`) VALUES ('order_submit_success_', 'BSN Spartan Data Center Notification: Order Submitted', 'We are pleased to inform you that we have received your order. Please complete the payment.<br/>Your order information is as follows:<br/>Order Number: ${trade_no_}<br/>Wallet: ${account_address_}<br/>Gas Credit Amount: ${gas_count_}<br/>Order Total: US$ ${pay_amount_}<br/>Payment Link: <a href=\'${pay_link_}\'>${pay_link_}</a>', 2, now(), now(), 1);
INSERT INTO `sys_message_template` (now()`msg_code`, `msg_title`, `msg_content`, `msg_type`, `update_time`, `create_time`, `state`) VALUES ('payment_success_', 'BSN Spartan Data Center Notification: Payment Success', 'We are pleased to inform you that we have received your order payment and we will recharge your Gas Credit and send the Gas Credit recharge result to your email address.<br/>Your order information is as follows:<br/>Order Number: ${trade_no_}<br/>Wallet: ${account_address_}<br/>Gas Credit Amount: ${gas_count_}<br/>Order Total: US$ ${pay_amount_}<br/>Payment Date: ${pay_time_}<br/> Transaction Hash: ${tx_hash_}', 2, now(), now(), 1);
INSERT INTO `sys_message_template` (now()`msg_code`, `msg_title`, `msg_content`, `msg_type`, `update_time`, `create_time`, `state`) VALUES ('keystorePasswordReset', 'BSN Spartan Data Center Notification: Re-configure Keystore Password', 'After restarting the service of the Data Center Management System, please configure the keystore password again or else the system cannot submit transactions to the chain.<br/><b>Operation step</b>: Click \'Configuration\' button and enter the keystore password in the Keystore Password section.', 2, now(), now(), 1);
INSERT INTO `sys_message_template` (now()`msg_code`, `msg_title`, `msg_content`, `msg_type`, `update_time`, `create_time`, `state`) VALUES ('gas_recharge_success_', 'BSN Spartan Data Center Notification: Emergency Gas Credit Top-up Processed', 'We are pleased to inform you that your recent Gas Credit top-up has been processed and you can check the balance here:${address_link_}<br/>Your transaction information is as follows:<br/>Order Number:${trade_no_}<br/>Wallet:${account_address_}<br/>Amount:${gas_count_}<br/>Order Total:US$${pay_amount_}<br/>Top-Up Time:${tx_time_}<br/>Transaction Hash:${tx_hash_}<br/><br/>Please check your Gas Credit balance.  You can get additional information via your Data Center Management System.', 2, now(), now(), 1);
INSERT INTO `sys_message_template` (now()`msg_code`, `msg_title`, `msg_content`, `msg_type`, `update_time`, `create_time`, `state`) VALUES ('keyStorePasswordConfig', 'BSN Spartan Data Center Notification: Configure Keystore Password', 'The system did not detect your keystore password and cannot submit transactions to the chain. Please log in to the Data Center Management System and configure the keystore password in the Keystore Password section.', 2, now(), now(), 1);
INSERT INTO `sys_message_template` (`msg_code`, `msg_title`, `msg_content`, `msg_type`, `update_time`, `create_time`,
                                    `state`)
VALUES ('gasBalanceReminderConfig', 'Insufficient Gas Credit',
        'Transactions cannot be submitted to the chain because there isn’t sufficient Gas Credit in your NTT Wallet Address. Please log in to the Data Center Management System and recharge the Gas Credit by clicking the Emergency button on the home page.',
        '2', now(), now(), '1');
INSERT INTO `sys_message_template` (`msg_code`, `msg_title`, `msg_content`, `msg_type`, `update_time`, `create_time`,
                                    `state`)
VALUES ('nttBalanceReminderConfig', 'Insufficient NTT',
        'Your NTT balance is insufficient. Please go to the <a href="https://spartan.bsn.foundation/main/top-up" target="_blank">Spartan Network Official Website</a> to purchase NTT.',
        '2', now(), now(), '1');


INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (1, 0, 'dashboard_', 'Home', '/index', 1, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (2, 0, 'node_module_', 'Node Management', 'javascript:;', 2, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (3, 0, 'ntt_module_', 'NTT History', '/ntt', 3, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (4, 0, 'chain_access_module_', 'Chain Access Management', 'javascript:;', 4, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (5, 0, 'charge_module_', 'Gas Credit Management', 'javascript:;', 5, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (6, 0, 'config_', 'Configuration', '/config', 6, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (7, 0, 'portal_config_', 'Portal Management', 'javascript:;', 7, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (8, 0, 'financial_module_', 'Financial Management', 'javascript:;', 8, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (9, 0, 'user_module_', 'User Management', 'javascript:;', 9, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (10, 0, 'support_menu_', 'BSN Technical Support', '/support', 10, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (11, 4, 'chain_access_config_', 'Access Configuration', '/chainAccess', 1, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (12, 4, 'user_access_info_', 'Access Key Management', '/userAccess', 2, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (13, 5, 'charge_menu_', 'Gas Credit Management', '/recharge', 1, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (14, 5, 'price_menu_', 'Price Settings', '/price', 2, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (15, 2, 'chain_menu_', 'Chain Info', '/chain', 1, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (16, 2, 'node_menu_', 'Node Info', '/node', 2, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (17, 7, 'base_info_config_', 'Basic Information', '/baseInfo', 1, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (18, 7, 'technical_support_config_', 'Technical Support', '/technicalSupport', 2, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (19, 7, 'payment_type_config_', 'Payment Method', '/paymentType', 3, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (20, 8, 'order_menu_', 'Order Management', '/financial', 1, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (21, 8, 'refund_menu_', 'Refund Management', '/refund', 2, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (22, 9, 'user_manage_', 'User Management', '/user', 1, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (23, 9, 'role_manage_', 'Role Management', '/role', 2, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (24, 23, 'insert_but_', 'Add', 'javascript:;', 0, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (25, 23, 'disable_but_', 'Disable', 'javascript:;', 1, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (26, 23, 'enable_but_', 'Enable', 'javascript:;', 2, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (27, 23, 'update_but_', 'Edit', 'javascript:;', 3, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (28, 23, 'check_but_', 'Detail', 'javascript:;', 4, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (29, 22, 'insert_but_', 'Add', 'javascript:;', 0, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (30, 22, 'disable_but_', 'Disable', 'javascript:;', 1, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (31, 22, 'enable_but_', 'Enable', 'javascript:;', 2, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (32, 22, 'update_but_', 'Edit', 'javascript:;', 3, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (33, 22, 'check_but_', 'Detail', 'javascript:;', 4, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (34, 22, 'reset_but_', 'Reset Password', 'javascript:;', 5, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (35, 16, 'net_application_but_', 'Register', 'javascript:;', 1, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (36, 13, 'recharge_but_', 'Top Up Free Gas Credit', 'javascript:;', 1, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (37, 12, 'access_key_disable_but_', 'Disable', 'javascript:;', 1, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (38, 12, 'access_key_enable_but_', 'Enable', 'javascript:;', 2, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (39, 12, 'access_key_update_but_', 'Edit', 'javascript:;', 3, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (40, 13, 'top_up_but_', 'Top Up', 'javascript:;', 2, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (41, 14, 'add_price_but_', 'Add', 'javascript:;', 1, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (42, 14, 'audit_but_', 'Review', 'javascript:;', 2, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (43, 14, 'detail_but_', 'Details', 'javascript:;', 3, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (44, 20, 'export_order_but', 'Export', 'javascript:;', 1, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (45, 20, 'detail_but_', 'Details', 'javascript:;', 2, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (46, 20, 'refund_but_', 'Refund', 'javascript:;', 3, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (47, 20, 'remittance_but_', 'Remittance', 'javascript:;', 4, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (48, 7, 'payment_term_menu_', 'Terms of Service', '/paymentTerm', 4, 1, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (49, 21, 'export_refund_', 'Export', 'javascript:;', 1, 2, 1);
INSERT INTO `sys_resource` (`rsuc_id`, `parent_id`, `rsuc_code`, `rsuc_name`, `rsuc_url`, `priority`, `rsuc_type`, `state`) VALUES (51, 6, 'delete_keystore_', 'Delete', 'javascript:;', 1, 2, 1);


INSERT INTO `sys_role` (`role_id`, `role_code`, `role_name`, `description`, `create_user`, `create_date`, `update_user`, `update_date`, `state`) VALUES (1, 'R0001', 'Admin', 'Admin', 1, now(), 0, now(), 1);

insert into sys_role_resource(role_id, rsuc_id)
select 1, rsuc_id
from sys_resource
where state = 1;

INSERT INTO `sys_user_role` (`user_role_id`, `user_id`, `role_id`) VALUES (1, 1, 1);
